#!/bin/bash 

# Keep Alive/Low resources Script for firefox
# This uses mostly marionette for the injection of a javascript and to control firefox. 
# I have found setting the settings with marionette are more elegant and better than attempting to do any "hardware clicks"

# using the default firefox profile location and searching for it to make sure. Using absolute path to prevent issues with cronjob
FF_PROFILE_DIR=$(find /home/$(whoami)/.mozilla/firefox -maxdepth 1 -type d -name "*.default*" | head -n 1)
# now injecting in settings that will streamline firefox and make it more suitable to low memory locations such as a Nuc as requested 
# this ensures that the settings are not changed by firefox who seems to have a very odd behavior on certain settings
if [ -n "$FF_PROFILE_DIR" ]
then
cat <<EOF > "$FF_PROFILE_DIR/user.js"
// disable disk cache to prevent io overhead
user_pref("browser.cache.disk.enable", false);
// set limited memory 
user_pref("browser.cache.memory.enable", true);
// set to 256 M
user_pref("browser.cache.memory.capacity", 256000);
// limit the number of processes allowed
user_pref("dom.ipc.processCount", 2);
// remove extra telemetry and other items
user_pref("toolkit.telemetry.enabled", false);
user_pref("extensions.pocket.enabled", false);
// set javascript to aggressively manage memory
user_pref("javascript.options.mem.max", 1024);
EOF
fi 

# echo to allow logging and make sure any cronjob functions
echo "$(date): Starting Firefox Refresh script"

# python scripting

/usr/bin/python3 - <<EOF

# load marionette driver so we can control firefox and time so there is a delay for the vm to load the page

from marionette_driver.marionette import Marionette
import time

# trying to connect to marionette browser and start a session

try:
	client = Marionette(host='localhost', port=2828)
	client.start_session()

# attempt to reload the page, since I have found due to the complicated webpage it can crash in low memory vm enviroments
	client.execute_script("location.reload(true);")

	try: 
    # since we are refreshing the page, I am going into the storage of the defaults for the player and setting to them required settings of unmutted and playing
		client.execute_script("localStorage.setItem('video-muted', '{\default\"false}');")
		client.execute_script("LocalStorage.setItem('volume', '1.0');")
	except:
		# if we are not able to, we just pass along so far this method has never failed
       pass

    # delay 20 seconds due to possible low memory enviroments needing more time to load the page elements 
	time.sleep(20)

  # javascript injection using HTML5 grab the video element and set it to play if paused. return sueccess if it works.
	umute_script = """
	let video = document.querySelector('video');
	if(video) {
		if(video.paused)
		  {
			video.play();
		  }
		return "Success";
	} else {
		return "Error Could not play"
	}
	"""
# running the script
client.execute_script(umute_script);

# return a cannot connect error cause marionette is either not enabled or browser is not open. 

except Exception as e:
	print(f"Failed to connect: {e}")
# clean up sessions
finally:
	#  if the client session still exists
	if 'client' in locals(): 
		try: 
			# delete it
			client.delete_session()
		except Exception:
			pass # the client session is dead don't need to kill it. 

EOF
